### ISSUE TITLE
exiftool coordinate format

### ISSUE THREAD

**Issue by VladimirKalachikhin** [otto-dev/coordinate-parser#2]
The `exiftool`, a tool to manipulate metainformation in images, get coordinates in format:
```
$ exiftool -EXIF:GPSLatitude -EXIF:GPSLongitude SV501357.jpg
GPS Latitude                    : 61 deg 49' 49.41"
GPS Longitude                   : 28 deg 54' 11.02"
```
or
```
$ exiftool -ee -p '$gpslatitude, $gpslongitude' SV501357.jpg
61 deg 49' 49.41" N, 28 deg 54' 11.02" E
```
but ***coordinate-parser*** do not accept this format.

Is it possible to add support for this as well?

**Comment by otto-dev** [comment]
Has been years since I wrote this code, but if the numerical format resembles other supported formats (apart from `deg` and non-numerical characters) then it should be quite straight forward to add. I'll have a quick look when I find time

**Comment by otto-dev** [comment]
Better late than never:

```js
new Coordinates(exif.replace(/deg/g, ''));
```

I think we can leave the burden on the user to do some basic pre-processing if that's required specifically for a particular tool. The tool is flexible enough to do so without having to write your own library. The error-message is meaningful too: `Coordinate contains invalid alphanumeric characters.`

Closing, but please let me know if there is anything I didn't consider.
