### ISSUE TITLE
Using - as degrees/minutes separator leads to incorrect parse

### ISSUE THREAD

**Issue by ojb500** [otto-dev/coordinate-parser#3]
Hi,

I'm trying to parse a position of the form `46-13.4N 004-26.2E` (degrees and decimal minutes)

coordinate-parser returns a latitude of ~45.776 - it seems to be parsing `-13.4` as the minutes component, not recognising that `-` is being used as the separator here.

Of course I can hack around this quickly by replacing `-` with some other character, but I think negative numbers should only ever be allowed in the first `latitudeNumber` or `longitudeNumber`, and any signs in second or later substrings should be ignored.

Thanks!

https://runkit.com/embed/m2x612spyitu

**Comment by otto-dev** [comment]
Makes sense. Implemented in #7
